### PR TITLE
Upgrade ruby to 3.2.0

### PR DESCRIPTION
**Pull request by xmunoz**
I rule and have completed some work on Case Manager that's ready for review!

Basically this PR, but without renovate: #2792

### CODE REVIEW

**Comment by xmunoz** [comment]
JK, looks like there are breaking changes in this upgrade.

**Comment by xmunoz** [comment]
Down to only 2 errors.

**Comment by xmunoz** [comment]
I give up

**Comment by xmunoz** [comment]
@colinxfleming @lomky can one of you take a look?

**Comment by colinxfleming** [comment]
it looks like you have it in a good state here and the failures are bullet related, which is probably a bs error. I'm gonna try downgrading bullet

**Pull request merged**
