### PR TITLE
Refine throttling on password and auth routes

### PR DESCRIPTION
**Pull request by djohnston32**
I rule and have completed some work on Case Manager that's ready for review!

Sets dedicated rate limits on key authentication and password routes to protect against attacks or spamming. Also narrows window for checking the general ip rate limit.

This pull request makes the following changes:
* Add throttling rules for /users/auth routes and /users/password routes
* Check ip limit every 10 seconds instead of every 5 minutes. The 60rpm limit stays the same, it's just checked more often (10 requests / 10 seconds vs. 300 requests / 300 seconds).
* Clear rails cache between rack-attack tests so we don't have to worry about ips or emails conflicting across tests.

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by djohnston32** [comment]
Even before my changes, I'm not able to trigger any of the throttling rules in my dev environment, and the tests for exceeding throttling limits always fail. Is there an option I can set somewhere so I can verify these changes locally?

**Comment by krbullock** [comment]
> Even before my changes, I'm not able to trigger any of the throttling rules in my dev environment, and the tests for exceeding throttling limits always fail. Is there an option I can set somewhere so I can verify these changes locally?

Maybe it's hitting [the bit that excludes localhost](https://github.com/DARIAEngineering/dcaf_case_management/blob/main/config/initializers/rack-attack.rb#L16-L19) from the limits — can you trigger them if you comment that bit out?

**Comment by djohnston32** [comment]
I had the same thought but it doesn't seem to trigger even with the localhost safelist rule commented out.

**Comment by djohnston32** [comment]
Ah, figured it out. Rack-attack depends on caching which is disabled by default in development and test environments. I can see now that some of the new limits I set are too aggressive so I'll send out a revision after I make some improvements.

**Comment by djohnston32** [comment]
Updated general rate limit by ip to 60 requests / 60 seconds in new revision. I as getting 503s during normal usage with 10/10, but 300/300 seemed too high. With 60/60 I only got throttled when simulating bad behavior, and normal operation didn't trigger it.

Also manually verified 5 requests / 20 seconds for password and auth routes were working properly, and verified all rack-attack tests were passing with caching enabled.

**Review by colinxfleming — APPROVED** [review]
nicely done! thank you for the dive through rack-attack configs!

**Comment by colinxfleming** [comment]
(and through the very particular development environment configuration)

**Pull request merged**
