### PR TITLE
Eli/2575 test trim urgent

### LINKED ISSUE #2575: trim_urgent_patients test
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Test our methods!

* **How could we solve this issue? (Not knowing is okay!)**
We're currently skipping the `trim_urgent_patients` test! We probably shouldn't! (as far as I can tell this is the only test we skip.)

https://github.com/DARIAEngineering/dcaf_case_management/blob/ba8f7ecc12cf5680076e07290198c6d7920ccc31/test/models/patient_test.rb#L349-L353

* **Anything else?**

There may be a reason we didn't test it, may be worth a `git blame` archaeology dig.

### PR DESCRIPTION
**Pull request by elimbaum**
I rule and have completed some work on Case Manager that's ready for review!

This pull request makes the following changes:
* Implements a test for the trim urgent/flagged patients method
* (another change here)
* (etc)

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #2575 
* Blocked by #2576 
* Bumps #Y

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by colinxfleming** [comment]
37 files changed! Think there might be some extra in this one, haha. I'll come back to it after the other urgents pr gets square.

**Comment by elimbaum** [comment]
haha yes just branched off of #2576

**Comment by elimbaum** [comment]
this will need a refactor w the new language

**Comment by elimbaum** [comment]
new language will make this too annoying. starting over

**Pull request closed without merging**
