### PR TITLE
Replace Turbolinks with Turbo

### LINKED ISSUE #2667: help tooltips being displayed twice on navigation
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
on navigation away from the patient information page, the help tooltips (`(?)`) are momentarily doubled up. weird! see screenshot below.

* **What feature or behavior is this required for?**
good user interface

* **How could we solve this issue? (Not knowing is okay!)**
may need to run a debugger in browser to figure out what's causing this! could be something with turbolinks, but I don't know why the help tooltips are the _only_ UI element being doubled.

* **Anything else?**

screenshot:

Screen Shot 2022-07-26 at 22 03 22

### PR DESCRIPTION
**Pull request by elimbaum**
I rule and have completed some work on Case Manager that's ready for review!

Turbolinks is [dead](https://github.com/turbolinks/turbolinks) but has been reborn as Turbo (with a [Rails-flavored integration](https://github.com/hotwired/turbo-rails))!

This pull request makes the following changes:
* Removes turbolinks
* Replaces with Turbo
* Compare with #2841 

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #2667 
* Bumps #Y

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by elimbaum** [comment]
- Ah, nevermind on it being quite so easy. Seems like [handling form submissions](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission) is tricky.

**Comment by colinxfleming** [comment]
I think we can ditch this; more trouble than it's worth

**Comment by colinxfleming** [comment]
sorry, didn't mean to close! but yeah, if you agree go ahead and close

**Comment by elimbaum** [comment]
ya lets get rid of it

**Pull request closed without merging**
